package fr.nicoos.alerte;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 static final String BASE="https://sjlzixjwynzyjrejlfup.supabase.co";
 static final String KEY="sb_publishable_qzvdETxohK5sPU3xHndM5w_WIL1rYW4";
 static final int BG=Color.rgb(8,13,25), PANEL=Color.rgb(17,26,47), TEXT=Color.rgb(247,248,255), MUTED=Color.rgb(154,168,199), CYAN=Color.rgb(56,200,255), GREEN=Color.rgb(53,208,127), ORANGE=Color.rgb(255,159,67), RED=Color.rgb(255,85,114), SECONDARY=Color.rgb(38,55,93);
 final ExecutorService exec=Executors.newSingleThreadExecutor();
 SharedPreferences prefs; LinearLayout root,loginBox,appBox,followBox; TextView urgency,project,task,date,status,msg; EditText email,password,nextTask; Button nextDateButton; String nextDate="",accessToken="",refreshToken="",userId=""; long currentTaskId=-1,currentProjectId=-1; String currentPriority=null;
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("nico_auth",MODE_PRIVATE);accessToken=prefs.getString("access","");refreshToken=prefs.getString("refresh","");userId=prefs.getString("uid","");buildUi();if(!accessToken.isEmpty()||!refreshToken.isEmpty()){showApp();loadTask();}else showLogin();}
 TextView tv(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setPadding(4,10,4,10);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
 Button btn(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(c==GREEN?Color.rgb(6,19,12):Color.WHITE);b.setBackgroundColor(c);return b;}
 EditText input(String h,boolean pass){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(MUTED);e.setTextColor(TEXT);e.setBackgroundColor(Color.rgb(24,35,61));e.setPadding(18,14,18,14);if(pass)e.setInputType(0x81);return e;}
 void buildUi(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(BG);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,44,28,44);sc.addView(root);setContentView(sc);loginBox=new LinearLayout(this);loginBox.setOrientation(LinearLayout.VERTICAL);loginBox.setPadding(24,24,24,24);loginBox.setBackgroundColor(PANEL);loginBox.addView(tv("◉  NICO OS ALERTE",25,CYAN,true));loginBox.addView(tv("Tes projets. Ta prochaine action.",16,MUTED,false));email=input("E-mail",false);password=input("Mot de passe",true);loginBox.addView(email);loginBox.addView(password);Button li=btn("SE CONNECTER",GREEN),su=btn("CRÉER MON COMPTE",SECONDARY);loginBox.addView(li);loginBox.addView(su);msg=tv("",13,MUTED,false);loginBox.addView(msg);li.setOnClickListener(v->auth(false));su.setOnClickListener(v->auth(true));root.addView(loginBox);appBox=new LinearLayout(this);appBox.setOrientation(LinearLayout.VERTICAL);appBox.setPadding(24,24,24,24);appBox.setBackgroundColor(PANEL);appBox.addView(tv("◉  NICO OS",22,CYAN,true));urgency=tv("Chargement…",32,CYAN,true);project=tv("",17,Color.BLACK,true);task=tv("",22,TEXT,true);date=tv("",18,ORANGE,true);status=tv("",13,MUTED,false);appBox.addView(urgency);appBox.addView(project);appBox.addView(task);appBox.addView(date);LinearLayout row=new LinearLayout(this);Button done=btn("✓ FAIT",GREEN),refresh=btn("↻ ACTUALISER",SECONDARY);row.addView(done,new LinearLayout.LayoutParams(0,-2,1));row.addView(refresh,new LinearLayout.LayoutParams(0,-2,1));appBox.addView(row);done.setOnClickListener(v->markDone());refresh.setOnClickListener(v->loadTask());followBox=new LinearLayout(this);followBox.setOrientation(LinearLayout.VERTICAL);followBox.addView(tv("Quelle est la prochaine étape de ce projet ?",17,TEXT,true));nextTask=input("Prochaine tâche",false);followBox.addView(nextTask);nextDateButton=btn("CHOISIR LA DATE",SECONDARY);followBox.addView(nextDateButton);Button add=btn("＋ AJOUTER",GREEN),skip=btn("PAS MAINTENANT",SECONDARY);followBox.addView(add);followBox.addView(skip);followBox.setVisibility(View.GONE);appBox.addView(followBox);nextDateButton.setOnClickListener(v->pickDate());add.setOnClickListener(v->addNext());skip.setOnClickListener(v->{followBox.setVisibility(View.GONE);loadTask();});appBox.addView(status);Button logout=btn("SE DÉCONNECTER",SECONDARY);appBox.addView(logout);logout.setOnClickListener(v->logout());root.addView(appBox);}
 void showLogin(){loginBox.setVisibility(View.VISIBLE);appBox.setVisibility(View.GONE);} void showApp(){loginBox.setVisibility(View.GONE);appBox.setVisibility(View.VISIBLE);}
 void auth(boolean signup){String em=email.getText().toString().trim(),pw=password.getText().toString();if(em.isEmpty()||pw.isEmpty()){msg.setText("E-mail et mot de passe requis.");return;}exec.execute(()->{try{String path=signup?"/auth/v1/signup":"/auth/v1/token?grant_type=password";JSONObject b=new JSONObject().put("email",em).put("password",pw);JSONObject j=new JSONObject(request("POST",BASE+path,b.toString(),false));if(j.has("access_token")){saveSession(j);runOnUiThread(()->{showApp();loadTask();});}else runOnUiThread(()->msg.setText("Compte créé. Vérifie ton e-mail si demandé."));}catch(Exception e){runOnUiThread(()->msg.setText(clean(e)));}});}
 void saveSession(JSONObject j){accessToken=j.optString("access_token","");refreshToken=j.optString("refresh_token","");JSONObject u=j.optJSONObject("user");if(u!=null)userId=u.optString("id","");prefs.edit().putString("access",accessToken).putString("refresh",refreshToken).putString("uid",userId).apply();}
 boolean refreshSession(){if(refreshToken.isEmpty())return false;try{JSONObject j=new JSONObject(request("POST",BASE+"/auth/v1/token?grant_type=refresh_token",new JSONObject().put("refresh_token",refreshToken).toString(),false));saveSession(j);return true;}catch(Exception e){return false;}}
 String request(String method,String url,String body,boolean auth)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setRequestProperty("apikey",KEY);c.setRequestProperty("Content-Type","application/json");if(auth&&!accessToken.isEmpty())c.setRequestProperty("Authorization","Bearer "+accessToken);if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=(code>=200&&code<300)?c.getInputStream():c.getErrorStream();String out=readAll(in);if(code==401&&auth&&refreshSession())return request(method,url,body,true);if(code<200||code>=300)throw new Exception(out.isEmpty()?"HTTP "+code:out);return out;}
 String readAll(InputStream in)throws Exception{if(in==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);return s.toString();}
 void loadTask(){followBox.setVisibility(View.GONE);status.setText("Synchronisation…");exec.execute(()->{try{JSONArray a=new JSONArray(request("GET",BASE+"/rest/v1/nico_tasks?select=id,title,project_id,priority,due,duration,done,nico_projects(name)&done=eq.false&order=due.asc.nullslast&limit=1",null,true));runOnUiThread(()->render(a));}catch(Exception e){runOnUiThread(()->status.setText(clean(e)));}});}
 void render(JSONArray a){try{status.setText("");if(a.length()==0){currentTaskId=-1;currentProjectId=-1;urgency.setText("TOUT EST À JOUR ✓");urgency.setTextColor(GREEN);project.setText("");task.setText("Aucune tâche en attente.");date.setText("");return;}JSONObject j=a.getJSONObject(0);currentTaskId=j.getLong("id");currentProjectId=j.optLong("project_id",-1);currentPriority=j.optString("priority",null);String due=j.optString("due",""),title=j.optString("title","Tâche");JSONObject p=j.optJSONObject("nico_projects");String pn=p!=null?p.optString("name","Sans projet"):"Sans projet";Due d=dueInfo(due);urgency.setText(d.label);urgency.setTextColor(d.color);project.setText("  "+pn+"  ");project.setBackgroundColor(d.color);task.setText(title);date.setText("ÉCHÉANCE • "+d.pretty);date.setTextColor(d.color);}catch(Exception e){status.setText(clean(e));}}
 static class Due{String label,pretty;int color;Due(String l,String p,int c){label=l;pretty=p;color=c;}}
 Due dueInfo(String s){if(s==null||s.isEmpty())return new Due("SANS DATE","",CYAN);try{SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.FRANCE);Date d=f.parse(s),n=f.parse(f.format(new Date()));long x=(d.getTime()-n.getTime())/86400000L;String p=new SimpleDateFormat("dd MMMM yyyy",Locale.FRANCE).format(d);if(x<0)return new Due("EN RETARD • "+(-x)+" J",p,RED);if(x==0)return new Due("AUJOURD'HUI",p,ORANGE);if(x==1)return new Due("DEMAIN",p,ORANGE);return new Due("DANS "+x+" JOURS",p,CYAN);}catch(Exception e){return new Due("ÉCHÉANCE",s,CYAN);}}
 void markDone(){if(currentTaskId<0)return;long tid=currentTaskId,pid=currentProjectId;String pri=currentPriority;status.setText("Validation…");exec.execute(()->{try{request("PATCH",BASE+"/rest/v1/nico_tasks?id=eq."+tid,new JSONObject().put("done",true).toString(),true);JSONArray a=new JSONArray(request("GET",BASE+"/rest/v1/nico_tasks?select=id&project_id=eq."+pid+"&done=eq.false&limit=1",null,true));runOnUiThread(()->{if(pid>0&&a.length()==0){currentProjectId=pid;currentPriority=pri;task.setText("Tâche terminée ✓");followBox.setVisibility(View.VISIBLE);status.setText("");}else loadTask();});}catch(Exception e){runOnUiThread(()->status.setText(clean(e)));}});}
 void pickDate(){Calendar c=Calendar.getInstance();new DatePickerDialog(this,(v,y,m,d)->{nextDate=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d);nextDateButton.setText("ÉCHÉANCE • "+String.format(Locale.FRANCE,"%02d/%02d/%04d",d,m+1,y));},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
 void addNext(){String title=nextTask.getText().toString().trim();if(title.isEmpty()){Toast.makeText(this,"Écris la prochaine tâche.",Toast.LENGTH_SHORT).show();return;}long id=System.currentTimeMillis();status.setText("Ajout…");exec.execute(()->{try{JSONObject b=new JSONObject().put("id",id).put("title",title).put("project_id",currentProjectId).put("owner_id",userId).put("priority",currentPriority).put("duration",30).put("done",false);if(!nextDate.isEmpty())b.put("due",nextDate);else b.put("due",JSONObject.NULL);request("POST",BASE+"/rest/v1/nico_tasks",b.toString(),true);runOnUiThread(()->{nextTask.setText("");nextDate="";nextDateButton.setText("CHOISIR LA DATE");loadTask();});}catch(Exception e){runOnUiThread(()->status.setText(clean(e)));}});}
 void logout(){prefs.edit().clear().apply();accessToken=refreshToken=userId="";showLogin();}
 String clean(Exception e){String s=e.getMessage();if(s==null)return"Erreur réseau";return s.length()>240?s.substring(0,240):s;}
 @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
