name: nico_scouter_clean
description: Nico Scouter clean native Android object finder
publish_to: 'none'
version: 0.7.0+7

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ultralytics_yolo: ^0.6.13
  speech_to_text: ^7.4.0
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/yoloe-26s-seg-pf_w8a32.tflite
